# Generated by Django 3.1.5 on 2021-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='firstFrame',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
