# Generated by Django 3.1.5 on 2021-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0005_video_firstframeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='basename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
