# Generated by Django 3.1.5 on 2021-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0006_video_basename'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='headFrameURL',
            field=models.CharField(default='', max_length=200),
        ),
    ]
