# Generated by Django 3.1.5 on 2021-01-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0007_video_headframeurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='firstFrameURL',
            new_name='oneFrameURL',
        ),
    ]
